//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GltfLoader.Schema
{
    using System.Linq;
    using System.Runtime.Serialization;
    
    
    public class BufferView
    {
        
        /// <summary>
        /// Backing field for Buffer.
        /// </summary>
        private int _buffer;
        
        /// <summary>
        /// Backing field for Byteoffset.
        /// </summary>
        private int _byteoffset = 0;
        
        /// <summary>
        /// Backing field for Bytelength.
        /// </summary>
        private int _bytelength;
        
        /// <summary>
        /// Backing field for Bytestride.
        /// </summary>
        private System.Nullable<int> _bytestride;
        
        /// <summary>
        /// Backing field for Target.
        /// </summary>
        private System.Nullable<GltfTarget> _target;
        
        /// <summary>
        /// Backing field for Name.
        /// </summary>
        private string _name;
        
        /// <summary>
        /// Backing field for Extensions.
        /// </summary>
        private System.Collections.Generic.Dictionary<string, object> _extensions;
        
        /// <summary>
        /// Backing field for Extras.
        /// </summary>
        private Extras _extras;
        
        /// <summary>
        /// The index of the buffer.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("buffer")]
        public int Buffer
        {
            get
            {
                return this._buffer;
            }
            set
            {
                if ((value < 0F))
                {
                    throw new System.ArgumentOutOfRangeException("Buffer", value, "Expected value to be greater than or equal to 0");
                }
                this._buffer = value;
            }
        }
        
        /// <summary>
        /// The offset into the buffer in bytes.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("byteOffset")]
        public int Byteoffset
        {
            get
            {
                return this._byteoffset;
            }
            set
            {
                if ((value < 0F))
                {
                    throw new System.ArgumentOutOfRangeException("Byteoffset", value, "Expected value to be greater than or equal to 0");
                }
                this._byteoffset = value;
            }
        }
        
        /// <summary>
        /// The total byte length of the buffer view.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("byteLength")]
        public int Bytelength
        {
            get
            {
                return this._bytelength;
            }
            set
            {
                if ((value < 1F))
                {
                    throw new System.ArgumentOutOfRangeException("Bytelength", value, "Expected value to be greater than or equal to 1");
                }
                this._bytelength = value;
            }
        }
        
        /// <summary>
        /// The stride, in bytes.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("byteStride")]
        public System.Nullable<int> Bytestride
        {
            get
            {
                return this._bytestride;
            }
            set
            {
                if ((value < 4F))
                {
                    throw new System.ArgumentOutOfRangeException("Bytestride", value, "Expected value to be greater than or equal to 4");
                }
                if ((value > 252F))
                {
                    throw new System.ArgumentOutOfRangeException("Bytestride", value, "Expected value to be less than or equal to 252");
                }
                this._bytestride = value;
            }
        }
        
        /// <summary>
        /// The target that the GPU buffer should be bound to.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("target")]
        public System.Nullable<GltfTarget> Target
        {
            get
            {
                return this._target;
            }
            set
            {
                this._target = value;
            }
        }
        
        /// <summary>
        /// The user-defined name of this object.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("name")]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        /// <summary>
        /// Dictionary object with extension-specific objects.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("extensions")]
        public System.Collections.Generic.Dictionary<string, object> Extensions
        {
            get
            {
                return this._extensions;
            }
            set
            {
                this._extensions = value;
            }
        }
        
        /// <summary>
        /// Application-specific data.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("extras")]
        public Extras Extras
        {
            get
            {
                return this._extras;
            }
            set
            {
                this._extras = value;
            }
        }
        
        public bool ShouldSerializeByteoffset()
        {
            return ((_byteoffset == 0) 
                        == false);
        }
        
        public bool ShouldSerializeBytestride()
        {
            return ((_bytestride == null) 
                        == false);
        }
        
        public bool ShouldSerializeTarget()
        {
            return ((_target == null) 
                        == false);
        }
        
        public bool ShouldSerializeName()
        {
            return ((_name == null) 
                        == false);
        }
        
        public bool ShouldSerializeExtensions()
        {
            return ((_extensions == null) 
                        == false);
        }
        
        public bool ShouldSerializeExtras()
        {
            return ((_extras == null) 
                        == false);
        }
        
        public enum GltfTarget
        {
            
            ArrayBuffer = 34962,
            
            ElementArrayBuffer = 34963,
        }
    }
}
