//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GltfLoader.Schema
{
    using System.Linq;
    using System.Runtime.Serialization;
    
    
    public class CameraOrthographic
    {
        
        /// <summary>
        /// Backing field for Xmag.
        /// </summary>
        private float _xmag;
        
        /// <summary>
        /// Backing field for Ymag.
        /// </summary>
        private float _ymag;
        
        /// <summary>
        /// Backing field for Zfar.
        /// </summary>
        private float _zfar;
        
        /// <summary>
        /// Backing field for Znear.
        /// </summary>
        private float _znear;
        
        /// <summary>
        /// Backing field for Extensions.
        /// </summary>
        private System.Collections.Generic.Dictionary<string, object> _extensions;
        
        /// <summary>
        /// Backing field for Extras.
        /// </summary>
        private Extras _extras;
        
        /// <summary>
        /// The floating-point horizontal magnification of the view. Must not be zero.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("xmag")]
        public float Xmag
        {
            get
            {
                return this._xmag;
            }
            set
            {
                this._xmag = value;
            }
        }
        
        /// <summary>
        /// The floating-point vertical magnification of the view. Must not be zero.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("ymag")]
        public float Ymag
        {
            get
            {
                return this._ymag;
            }
            set
            {
                this._ymag = value;
            }
        }
        
        /// <summary>
        /// The floating-point distance to the far clipping plane. `zfar` must be greater than `znear`.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("zfar")]
        public float Zfar
        {
            get
            {
                return this._zfar;
            }
            set
            {
                if ((value <= 0F))
                {
                    throw new System.ArgumentOutOfRangeException("Zfar", value, "Expected value to be greater than 0");
                }
                this._zfar = value;
            }
        }
        
        /// <summary>
        /// The floating-point distance to the near clipping plane.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("znear")]
        public float Znear
        {
            get
            {
                return this._znear;
            }
            set
            {
                if ((value < 0F))
                {
                    throw new System.ArgumentOutOfRangeException("Znear", value, "Expected value to be greater than or equal to 0");
                }
                this._znear = value;
            }
        }
        
        /// <summary>
        /// Dictionary object with extension-specific objects.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("extensions")]
        public System.Collections.Generic.Dictionary<string, object> Extensions
        {
            get
            {
                return this._extensions;
            }
            set
            {
                this._extensions = value;
            }
        }
        
        /// <summary>
        /// Application-specific data.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("extras")]
        public Extras Extras
        {
            get
            {
                return this._extras;
            }
            set
            {
                this._extras = value;
            }
        }
        
        public bool ShouldSerializeExtensions()
        {
            return ((_extensions == null) 
                        == false);
        }
        
        public bool ShouldSerializeExtras()
        {
            return ((_extras == null) 
                        == false);
        }
    }
}
