//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GltfLoader.Schema
{
    using System.Linq;
    using System.Runtime.Serialization;
    
    
    public class Mesh
    {
        
        /// <summary>
        /// Backing field for Primitives.
        /// </summary>
        private MeshPrimitive[] _primitives;
        
        /// <summary>
        /// Backing field for Weights.
        /// </summary>
        private float[] _weights;
        
        /// <summary>
        /// Backing field for Name.
        /// </summary>
        private string _name;
        
        /// <summary>
        /// Backing field for Extensions.
        /// </summary>
        private System.Collections.Generic.Dictionary<string, object> _extensions;
        
        /// <summary>
        /// Backing field for Extras.
        /// </summary>
        private Extras _extras;
        
        /// <summary>
        /// An array of primitives, each defining geometry to be rendered with a material.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("primitives")]
        public MeshPrimitive[] Primitives
        {
            get
            {
                return this._primitives;
            }
            set
            {
                if ((value == null))
                {
                    this._primitives = value;
                    return;
                }
                if ((value.Length < 1u))
                {
                    throw new System.ArgumentException("Array not long enough");
                }
                this._primitives = value;
            }
        }
        
        /// <summary>
        /// Array of weights to be applied to the Morph Targets.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("weights")]
        public float[] Weights
        {
            get
            {
                return this._weights;
            }
            set
            {
                if ((value == null))
                {
                    this._weights = value;
                    return;
                }
                if ((value.Length < 1u))
                {
                    throw new System.ArgumentException("Array not long enough");
                }
                this._weights = value;
            }
        }
        
        /// <summary>
        /// The user-defined name of this object.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("name")]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        /// <summary>
        /// Dictionary object with extension-specific objects.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("extensions")]
        public System.Collections.Generic.Dictionary<string, object> Extensions
        {
            get
            {
                return this._extensions;
            }
            set
            {
                this._extensions = value;
            }
        }
        
        /// <summary>
        /// Application-specific data.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("extras")]
        public Extras Extras
        {
            get
            {
                return this._extras;
            }
            set
            {
                this._extras = value;
            }
        }
        
        public bool ShouldSerializePrimitives()
        {
            return ((_primitives == null) 
                        == false);
        }
        
        public bool ShouldSerializeWeights()
        {
            return ((_weights == null) 
                        == false);
        }
        
        public bool ShouldSerializeName()
        {
            return ((_name == null) 
                        == false);
        }
        
        public bool ShouldSerializeExtensions()
        {
            return ((_extensions == null) 
                        == false);
        }
        
        public bool ShouldSerializeExtras()
        {
            return ((_extras == null) 
                        == false);
        }
    }
}
