//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GltfLoader.Schema
{
    using System.Linq;
    using System.Runtime.Serialization;
    
    
    public class Sampler
    {
        
        /// <summary>
        /// Backing field for Magfilter.
        /// </summary>
        private System.Nullable<GltfMagfilter> _magfilter;
        
        /// <summary>
        /// Backing field for Minfilter.
        /// </summary>
        private System.Nullable<GltfMinfilter> _minfilter;
        
        /// <summary>
        /// Backing field for Wraps.
        /// </summary>
        private GltfWraps _wraps = GltfWraps.Repeat;
        
        /// <summary>
        /// Backing field for Wrapt.
        /// </summary>
        private GltfWrapt _wrapt = GltfWrapt.Repeat;
        
        /// <summary>
        /// Backing field for Name.
        /// </summary>
        private string _name;
        
        /// <summary>
        /// Backing field for Extensions.
        /// </summary>
        private System.Collections.Generic.Dictionary<string, object> _extensions;
        
        /// <summary>
        /// Backing field for Extras.
        /// </summary>
        private Extras _extras;
        
        /// <summary>
        /// Magnification filter.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("magFilter")]
        public System.Nullable<GltfMagfilter> Magfilter
        {
            get
            {
                return this._magfilter;
            }
            set
            {
                this._magfilter = value;
            }
        }
        
        /// <summary>
        /// Minification filter.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("minFilter")]
        public System.Nullable<GltfMinfilter> Minfilter
        {
            get
            {
                return this._minfilter;
            }
            set
            {
                this._minfilter = value;
            }
        }
        
        /// <summary>
        /// s wrapping mode.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("wrapS")]
        public GltfWraps Wraps
        {
            get
            {
                return this._wraps;
            }
            set
            {
                this._wraps = value;
            }
        }
        
        /// <summary>
        /// t wrapping mode.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("wrapT")]
        public GltfWrapt Wrapt
        {
            get
            {
                return this._wrapt;
            }
            set
            {
                this._wrapt = value;
            }
        }
        
        /// <summary>
        /// The user-defined name of this object.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("name")]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
            }
        }
        
        /// <summary>
        /// Dictionary object with extension-specific objects.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("extensions")]
        public System.Collections.Generic.Dictionary<string, object> Extensions
        {
            get
            {
                return this._extensions;
            }
            set
            {
                this._extensions = value;
            }
        }
        
        /// <summary>
        /// Application-specific data.
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyNameAttribute("extras")]
        public Extras Extras
        {
            get
            {
                return this._extras;
            }
            set
            {
                this._extras = value;
            }
        }
        
        public bool ShouldSerializeMagfilter()
        {
            return ((_magfilter == null) 
                        == false);
        }
        
        public bool ShouldSerializeMinfilter()
        {
            return ((_minfilter == null) 
                        == false);
        }
        
        public bool ShouldSerializeWraps()
        {
            return ((_wraps == GltfWraps.Repeat) 
                        == false);
        }
        
        public bool ShouldSerializeWrapt()
        {
            return ((_wrapt == GltfWrapt.Repeat) 
                        == false);
        }
        
        public bool ShouldSerializeName()
        {
            return ((_name == null) 
                        == false);
        }
        
        public bool ShouldSerializeExtensions()
        {
            return ((_extensions == null) 
                        == false);
        }
        
        public bool ShouldSerializeExtras()
        {
            return ((_extras == null) 
                        == false);
        }
        
        public enum GltfMagfilter
        {
            
            Nearest = 9728,
            
            Linear = 9729,
        }
        
        public enum GltfMinfilter
        {
            
            Nearest = 9728,
            
            Linear = 9729,
            
            NearestMipmapNearest = 9984,
            
            LinearMipmapNearest = 9985,
            
            NearestMipmapLinear = 9986,
            
            LinearMipmapLinear = 9987,
        }
        
        public enum GltfWraps
        {
            
            ClampToEdge = 33071,
            
            MirroredRepeat = 33648,
            
            Repeat = 10497,
        }
        
        public enum GltfWrapt
        {
            
            ClampToEdge = 33071,
            
            MirroredRepeat = 33648,
            
            Repeat = 10497,
        }
    }
}
